title: Yijin's Writings
author: Yijin Lee
description: > # this means to ignore newlines until "show_exerpts:"
  Perhaps I should write things down more...
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /texture
url: https://blog.yijin.uk

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Yijin's Writings
  tagline: Chartered Engineer. Coder.
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    landing: https://yijin.uk
    twitter: yijin
    github:  yijinlee
    linkedIn: in/yijinlee
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
